version: '3.8'  # Specify your Docker Compose version

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "battery"
      PGOPTIONS: "-c max_connections=200"

volumes:
  postgres: